-- Initial schema: Monday=0; wall-clock timetable timezone Europe/Paris.
create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;
create table public.profiles(id uuid primary key references auth.users on delete cascade, username text not null check(length(trim(username)) between 2 and 60), created_at timestamptz not null default now());
create table public.groups(id uuid primary key default gen_random_uuid(), name text not null check(length(trim(name)) between 1 and 80), owner_id uuid not null references public.profiles on delete cascade, created_at timestamptz not null default now());
create table public.group_members(group_id uuid references public.groups on delete cascade, user_id uuid references public.profiles on delete cascade, joined_at timestamptz not null default now(), primary key(group_id,user_id));
create index members_user_idx on public.group_members(user_id,group_id);
create index groups_owner_idx on public.groups(owner_id);
create table public.invitations(id uuid primary key default gen_random_uuid(), group_id uuid not null references public.groups on delete cascade, token uuid not null unique default gen_random_uuid(), expires_at timestamptz not null default now()+interval '7 days', used_by uuid references public.profiles on delete set null, used_at timestamptz, revoked boolean not null default false);
create index invitations_group_idx on public.invitations(group_id);
create index invitations_user_idx on public.invitations(used_by);
create table public.events(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles on delete cascade, title text not null check(length(trim(title)) between 1 and 120), teacher text not null default '' check(length(teacher)<=120), room text not null default '' check(length(room)<=80), day_of_week smallint not null check(day_of_week between 0 and 6), start_time time not null, end_time time not null, recurrence_start date not null default current_date, recurrence_end date, created_at timestamptz not null default now(), check(end_time>start_time), check(recurrence_end is null or recurrence_end>=recurrence_start));
create index events_user_day_idx on public.events(user_id,day_of_week);
create table public.cancellations(id uuid primary key default gen_random_uuid(), group_id uuid not null references public.groups on delete cascade, event_id uuid not null references public.events on delete cascade, occurrence_date date not null, reported_by uuid not null references public.profiles on delete cascade, status text not null default 'pending' check(status in ('pending','confirmed','rejected')), created_at timestamptz not null default now(), unique(group_id,event_id,occurrence_date));
create index cancellations_event_idx on public.cancellations(event_id);
create index cancellations_reporter_idx on public.cancellations(reported_by);
create table public.cancellation_confirmations(cancellation_id uuid references public.cancellations on delete cascade, user_id uuid references public.profiles on delete cascade, confirmation boolean not null, primary key(cancellation_id,user_id));
create index confirmations_user_idx on public.cancellation_confirmations(user_id);
-- Privileged lookups are confined to a non-exposed schema to avoid recursive RLS.
create function private.is_member(g uuid) returns boolean language sql stable security definer set search_path='' as $$ select auth.uid() is not null and exists(select 1 from public.group_members where group_id=g and user_id=auth.uid()) $$;
create function private.is_peer(u uuid) returns boolean language sql stable security definer set search_path='' as $$ select auth.uid() is not null and (u=auth.uid() or exists(select 1 from public.group_members a join public.group_members b using(group_id) where a.user_id=auth.uid() and b.user_id=u)) $$;
create function private.new_user() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.profiles(id,username) values(new.id,left(coalesce(nullif(trim(new.raw_user_meta_data->>'username'),''),'Étudiant'),60)); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function private.new_user();
create function private.new_group() returns trigger language plpgsql security definer set search_path='' as $$ begin if auth.uid() is null or auth.uid()<>new.owner_id then raise exception 'Non autorisé'; end if; insert into public.group_members values(new.id,new.owner_id,now()); return new; end $$;
create trigger group_owner_member after insert on public.groups for each row execute function private.new_group();
create function private.accept_invitation(t uuid) returns uuid language plpgsql security definer set search_path='' as $$ declare i public.invitations; begin
 if auth.uid() is null then raise exception 'Connexion requise'; end if;
 select * into i from public.invitations where token=t for update;
 if not found or i.revoked or i.used_at is not null or i.expires_at<=now() then raise exception 'Invitation invalide ou expirée'; end if;
 insert into public.group_members(group_id,user_id) values(i.group_id,auth.uid()) on conflict do nothing;
 update public.invitations set used_by=auth.uid(),used_at=now() where id=i.id; return i.group_id; end $$;
create function public.accept_invitation(token uuid) returns uuid language sql security invoker set search_path='' as $$ select private.accept_invitation(token) $$;
create function private.report_absence(g uuid,e uuid,d date) returns uuid language plpgsql security definer set search_path='' as $$ declare ev public.events; c uuid; begin
 if not private.is_member(g) then raise exception 'Non autorisé'; end if;
 select * into ev from public.events where id=e;
 if not found or not exists(select 1 from public.group_members where group_id=g and user_id=ev.user_id) or (extract(isodow from d)::int-1)<>ev.day_of_week or d<ev.recurrence_start or d>coalesce(ev.recurrence_end,'infinity'::date) or d<(now() at time zone 'Europe/Paris')::date then raise exception 'Occurrence invalide'; end if;
 insert into public.cancellations(group_id,event_id,occurrence_date,reported_by) values(g,e,d,auth.uid()) returning id into c;
 insert into public.cancellation_confirmations values(c,auth.uid(),true); return c; end $$;
create function public.report_absence(group_id uuid,event_id uuid,occurrence_date date) returns uuid language sql security invoker set search_path='' as $$ select private.report_absence(group_id,event_id,occurrence_date) $$;
create function private.vote_absence(c uuid,v boolean) returns void language plpgsql security definer set search_path='' as $$ declare g uuid; yes int; no int; begin
 select group_id into g from public.cancellations where id=c for update;
 if g is null or not private.is_member(g) then raise exception 'Non autorisé'; end if;
 insert into public.cancellation_confirmations values(c,auth.uid(),v) on conflict(cancellation_id,user_id) do update set confirmation=excluded.confirmation;
 select count(*) filter(where confirmation),count(*) filter(where not confirmation) into yes,no from public.cancellation_confirmations where cancellation_id=c;
 update public.cancellations set status=case when yes>=2 and yes>no then 'confirmed' when no>=2 and no>=yes then 'rejected' else 'pending' end where id=c; end $$;
create function public.vote_absence(cancellation_id uuid,confirmation boolean) returns void language sql security invoker set search_path='' as $$ select private.vote_absence(cancellation_id,confirmation) $$;
alter table public.profiles enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.invitations enable row level security;
alter table public.events enable row level security;
alter table public.cancellations enable row level security;
alter table public.cancellation_confirmations enable row level security;
create policy profiles_read on public.profiles for select to authenticated using(private.is_peer(id));
create policy profiles_update on public.profiles for update to authenticated using(id=(select auth.uid())) with check(id=(select auth.uid()));
create policy groups_read on public.groups for select to authenticated using(private.is_member(id));
create policy groups_insert on public.groups for insert to authenticated with check(owner_id=(select auth.uid()));
create policy groups_update on public.groups for update to authenticated using(owner_id=(select auth.uid())) with check(owner_id=(select auth.uid()));
create policy groups_delete on public.groups for delete to authenticated using(owner_id=(select auth.uid()));
create policy members_read on public.group_members for select to authenticated using(private.is_member(group_id));
create policy members_delete on public.group_members for delete to authenticated using(user_id<>(select owner_id from public.groups where id=group_id) and (user_id=(select auth.uid()) or exists(select 1 from public.groups where id=group_id and owner_id=(select auth.uid()))));
create policy invites_read on public.invitations for select to authenticated using(exists(select 1 from public.groups where id=group_id and owner_id=(select auth.uid())));
create policy invites_insert on public.invitations for insert to authenticated with check(exists(select 1 from public.groups where id=group_id and owner_id=(select auth.uid())));
create policy invites_update on public.invitations for update to authenticated using(exists(select 1 from public.groups where id=group_id and owner_id=(select auth.uid()))) with check(exists(select 1 from public.groups where id=group_id and owner_id=(select auth.uid())));
create policy events_read on public.events for select to authenticated using(private.is_peer(user_id));
create policy events_insert on public.events for insert to authenticated with check(user_id=(select auth.uid()));
create policy events_update on public.events for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy events_delete on public.events for delete to authenticated using(user_id=(select auth.uid()));
create policy cancellations_read on public.cancellations for select to authenticated using(private.is_member(group_id));
create policy confirmations_read on public.cancellation_confirmations for select to authenticated using(exists(select 1 from public.cancellations where id=cancellation_id));
revoke all on public.profiles,public.groups,public.group_members,public.invitations,public.events,public.cancellations,public.cancellation_confirmations from anon,authenticated;
grant select on public.profiles,public.groups,public.group_members,public.invitations,public.events,public.cancellations,public.cancellation_confirmations to authenticated;
grant update(username) on public.profiles to authenticated;
grant insert(name,owner_id),update(name),delete on public.groups to authenticated;
grant delete on public.group_members to authenticated;
grant insert(group_id),update(revoked) on public.invitations to authenticated;
grant insert(user_id,title,teacher,room,day_of_week,start_time,end_time,recurrence_start,recurrence_end),update(title,teacher,room,day_of_week,start_time,end_time,recurrence_start,recurrence_end),delete on public.events to authenticated;
revoke execute on all functions in schema private from public,anon,authenticated;
grant execute on function private.is_member(uuid),private.is_peer(uuid),private.accept_invitation(uuid),private.report_absence(uuid,uuid,date),private.vote_absence(uuid,boolean) to authenticated;
revoke execute on function public.accept_invitation(uuid),public.report_absence(uuid,uuid,date),public.vote_absence(uuid,boolean) from public,anon;
grant execute on function public.accept_invitation(uuid),public.report_absence(uuid,uuid,date),public.vote_absence(uuid,boolean) to authenticated;
alter publication supabase_realtime add table public.profiles,public.groups,public.group_members,public.events,public.cancellations,public.cancellation_confirmations;
